version: '2'
services:
 api:
  build:
   context: ./api
   dockerfile: Dockerfile
# web:
#  build:
#   context: ./web
#   dockerfile: Dockerfile
 proxy:
   build:
     context: ./proxy
     dockerfile: Dockerfile
   ports:
    - "50080:80"