version: '2'
services:
 api:
  build:
   context: ./api
  restart: always
  env_file:
    - ".env"
  volumes:
    - "./google-cloud-key.secret:/config/gcloud.secret"
 web:
  build:
   context: ./web
  restart: always
 proxy:
   build:
     context: ./proxy
   ports:
    - "8080:80"
   restart: always
